### ISSUE TITLE
Deploy contracts to base

### ISSUE THREAD

**Issue by stevennevins** [0xSplits/splits-contracts#11]

**Comment by wminshew** [comment]
Hi @stevennevins -- splits are already on base https://docs.splits.org/core/split#addresses

**Comment by stevennevins** [comment]
Awesome! Ty for the quick response. I checked here for the info and didn’t see it in the deploy folder

**Comment by wminshew** [comment]
yeah you'd have to look in the other branches that are tagged with the other network names -- it's an admittedly odd git structure that we've changed in later repos for clarity

**Comment by stevennevins** [comment]
Gotcha, i noticed the one for sepolia is deployed at another address. is that intended or a mistake?

**Comment by wminshew** [comment]
> Gotcha, i noticed the one for sepolia is deployed at another address. is that intended or a mistake?

we try to be consistent but it isn't always possible unf
