### ISSUE TITLE
Sorting addresses on-chain

### ISSUE THREAD

**Issue by dave4506** [0xSplits/splits-contracts#3]
In the docs, there is a note implying that the addresses passed needs to be ordered; is this requirement just a need of making the split deterministic? 

If my protocol create splits can ensure the ordered addresses are in a order we understand would it work?

**Comment by wminshew** [comment]
no -- in the current deployment (v1), they must be sorted from smallest (address) to largest. The canonical ordering allows us to prevent duplicate immutable splits, match the hash & cheaply prevent duplicate recipients on-chain. In a future iteration (deployed in next couple of months?) it's likely we'll relax this requirement
