### ISSUE TITLE
SplitProxy Documentation

### ISSUE THREAD

**Issue by pynchmeister** [0xSplits/splits-contracts#6]
I'm reading through the smart contract documentation and I'm seeing a reference to SplitProxy here: https://docs.0xsplits.xyz/smartcontracts/overview#splitproxy that I cant find in the contract code. Can someone please point me in the right direction

**Comment by wminshew** [comment]
hey -- the proxy refers to the clone:

https://github.com/0xSplits/splits-contracts/blob/main/contracts/libraries/Clones.sol
https://github.com/0xSplits/splits-contracts/blob/main/contracts/SplitMain.sol#L274-L277

**Comment by pynchmeister** [comment]
Thanks that's what I figured I just wanted to bring it to your attention
